name: Docker Publish Backend

on:
  push:
    branches:
      - 'main'
      - 'feature/ipv6-dual-stack-default'
    paths:
      # Only run when relevant backend files change
      - 'crates/**'
      - 'self-hosted/docker-build/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get UTC ISO8601 timestamp
        run: echo "COMMIT_TIMESTAMP=$(git log -1 --format='%aI' | date -f - --utc '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: self-hosted/docker-build/Dockerfile.backend
          push: true
          tags: |
            ghcr.io/bai-admin/convex-backend:latest
            ghcr.io/bai-admin/convex-backend:${{ github.sha }}
          build-args: |
            VERGEN_GIT_SHA=${{ github.sha }}
            VERGEN_GIT_COMMIT_TIMESTAMP=${{ env.COMMIT_TIMESTAMP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 